### ISSUE TITLE
Open Data 500 Country Site

### ISSUE THREAD

**Issue by rdc112** [GovLab/OpenData500#127]
Change "The GovLab Open Data Listing" to "The GovLab Open Data 500 Network"

Add below The GovLab Open Data Network: 

The Open Data 500 Network is the first set of comprehensive studies of companies and NGOs using open data in countries around the world. 
 
Add: South Korea, Italy and Russia

Add: Coming Soon under Australia, South Korea, Italy, and Russia 

Delete "About this Initiative"

Add below countries:

To find out how to conduct a study in your country, please contact us at The GovLab at NYU. (point "contact us" to mailto:opendata500@thegovlab.org)

**Comment by talos** [comment]
Everything except

> Add: South Korea, Italy and Russia
>
> Add: Coming Soon under Australia, South Korea, Italy, and Russia 

Should be done now.  Because those will require some styling input from Claudio, I'm moving them into a separate issue.

@rdc112 Thank you for making the issue.  Please check in on http://opendata500.com/9/ and let me know if it looks right.  The flag changes are now in issue #128.
